### ISSUE TITLE
i couldnt work an oeshoot example in python on the linux

### ISSUE THREAD

**Issue by caglakuru** [antonior92/oe-multiple-shooting#1]
Hello,
I installed linux system on ubuntu and i followed all steps that you shown related to oe-multiple-shooting. Firstly,  i downloaded it from github and i installed all requirments, python setup.py and finally i run the python setup.py test. Program gave that ran 66 tests are OK.
And then i run the oeshoot example in the python but it gives the error that ModuleNotFoundError: No module named 'numpy'.

**Comment by antonior92** [comment]
It is super strange that the program passed all tests if numpy is not installed, since numpy is one of the dependencies of the package.

I would guess that you are trying to run the example in a different python installation or version than the one that you have actually used during the installation

**Comment by caglakuru** [comment]
I installed different python version and numpy medule worked with this version but now the system is giving the this error "Could not find a version that satisfies the requirement oeshoot (from versions: )
No matching distribution found for oeshoot" while i was writing the example 1.

How can i do ?

**Comment by caglakuru** [comment]
Hello,
I have alread had a new problem.

I installed different python version and numpy medule worked with this
version but now the system is giving the this error "Could not find a
version that satisfies the requirement oeshoot (from versions: )
No matching distribution found for oeshoot" while i was writing the example
1.

How can i do ?

Antonio Horta Ribeiro <notifications@github.com>, 29 Mar 2019 Cum, 16:57
tarihinde şunu yazdı:

**Comment by antonior92** [comment]
I think you need to install the oe-multiple-shooting package for this new version of python you have just installed. Maybe try to repeat the procedures described in the README.
